 <header class="menu">
            <a href="index.html" class="logo"><img src="../images/ava2-removebg-preview.png" alt="logo"></a>
            <nav class="nav-bar">
                <a href="./index.php">Home</a>
                <a href="./about.php">About Us</a>
                <a href="./jobs.php">Application</a>
            </nav>
            <div class="login">
                <a href="">Login</a>
            </div>
        </header>

       
        <div class="about_page">
            <div class="about_info">
                <h2 class="about_title">Who we are</h2>
                <p>Smarthouse is a pioneer in enhancing the mundane aspects of life. Our mission is to innovate and create technological solutions that simplify daily life while fostering deeper connections and facilitating growth in an ever-evolving digital world.</p>
            </div>

           
            <div class="about_info">
                <h2 class="about_title">History</h2>
                <p>In 2024, Minh, alongside Bao and Vinh, set forth on a transformative journey, founding Smarthouse with a clear mission: to innovate and simplify daily life in the digital age. From humble beginnings, our passion for technological excellence propelled us forward, earning recognition for our forward-thinking approach.<br>
                    Throughout our history, we've embraced change, adapting to emerging trends and technologies while staying true to our core values. Guided by our mission, every endeavor at Smarthouse is infused with purpose, aiming to simplify, connect, and empower in an ever-evolving digital world.<br>
                    As we look ahead, our journey continues, fueled by innovation and driven by purpose. Together, let's shape tomorrow's technology and transform lives for the better.
                </p>
            </div>

            <div class="about_info">
                <h2 class="about_title">Learn more</h2>
                <div class="about_links">
                    <div class="about_links_box">
                        <a href="team.html">
                            <img src="../images/team.jpg" alt="Team" class="about_image">
                        </a>
                        <a href="team.html" class="about_links_head">The Team</a>
                        <p class="about_links_desc">Find out more about us</p>
                    </div>
                    <div class="about_links_box">
                        <a href="">
                            <img src="../images/achievements.jpg" alt="Achievements & Partners" class="about_image">
                        </a>
                        <a href="" class="about_links_head">Achievements & Partners</a>
                        <p class="about_links_desc">Our accomplishments throughout the years</p>
                    </div>
                    <div class="about_links_box">
                        <a href="jobs.html">
                            <img src="../images/hiring.png" alt="Application" class="about_image">
                        </a>
                        <a href="jobs.html" class="about_links_head">Work for us</a>
                        <p class="about_links_desc">We are always looking for new talents</p>
                    </div>
                </div>
            </div>
        </div>
        <footer>
            <div class="row">
                <div class="col" id="special-col">
                    <img src="../images/ava2-removebg-preview.png" class="logo" alt="logo">
                </div>
                <div class="col" id="index_address">
                    <h3>Office<div class="underline"></div></h3>
                    <p class="address">80 Duy Tan<br>
                        Dich Vong Hau, Cau Giay<br>
                        Hanoi, Vietnam
                    </p>
                </div>
                <div class="col" id="index_links">
                    <h3>Links<div class="underline"></div></h3>
                    <ol class="index_links">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="about.html">About Us</a></li>
                        <li><a href="jobs.html">Job Description</a></li>
                    </ol>
                </div>
                <div class="col">
                    <h3>Any Question?</h3>
                    <form method="post" action="http://mercury.swin.edu.au/it000000/formtest.php">
                        <i class="fa-solid fa-inbox"></i>
                        <label for="inquiry" aria-label="inquiry">
                            <input type="text" id="inquiry" name="inquiry" placeholder="Ask here">
                        </label>
                        <button type="submit" class="fa-regular fa-paper-plane" aria-label="submit"></button>
                    </form>
                    <div class="social">
                        <a class="fa-brands fa-youtube" href="https://youtu.be/EXyGv1s0cfk">Youtube video</a>
                    </div>
                </div>
            </div>
        </footer>