<div class="row">
            <div class="col" id="special-col">
                <img src="../images/ava2-removebg-preview.png" class="logo" alt="logo">
            </div>
            <div class="col" id="index_address">
                <h3>Office<div class="underline"></div></h3>
                <p class="address">80 Duy Tan<br>
                    Dich Vong Hau, Cau Giay<br>
                    Hanoi, Vietnam
                </p>
            </div>
            <div class="col" id="index_links">
                <h3>Links<div class="underline"></div></h3>
                <ol class="index_links">
                    <li><a href="index.php">Home</a></li>
                    <li><a href="about.php">About Us</a></li>
                    <li><a href="jobs.php">Job Description</a></li>
                </ol>
            </div>
            <div class="col">
                <h3>Any Question?</h3>
                <form method="post" action="http://mercury.swin.edu.au/it000000/formtest.php">
                    <i class="fa-solid fa-inbox"></i>
                    <label for="inquiry" aria-label="inquiry">
                        <input type="text" id="inquiry" name="inquiry" placeholder="Ask here">
                    </label>
                    <button type="submit" class="fa-regular fa-paper-plane" aria-label="submit"></button>
                </form>
                <div class="social">
                    <a class="fa-brands fa-youtube" href="https://youtu.be/EXyGv1s0cfk">Youtube video</a>
                </div>
            </div>
        </div>