<header class="menu">
    <a href="index.php" class="logo"><img src="../images/ava2-removebg-preview.png" alt="logo"></a>
    <nav class="nav-bar">
        <a href="./index.php">Home</a>
        <a href="./about.php">About Us</a>
        <a href="./jobs.php">Application</a>
        <a href="./managerlogin.php">Manager login</a>
    </nav>
    <div class="login">
        <a href="login.php">Login</a>
    </div>
</header>