
        <header class="menu">
            <a href="index.html" class="logo"><img src="../images/ava2-removebg-preview.png" alt="logo"></a>
            <nav class="nav-bar">
                <a href="./index.php">Home</a>
                <a href="./about.php">About Us</a>
                <a href="./jobs.php">Application</a>
            </nav>
            <div class="login">
                <a href="">Login</a>
            </div>
        </header>

        <div class="jobs_page">
            
            <section class="title">
                <h1>IT and Developments</h1>
                <p>Thank you for your interest in the IT positions here at our company.<br>
                    We appreciate the time you've taken to consider joining our team.<br>
                    <br>
                    Here are the postions that we are currently hiring<br>
                    &nbsp;<!--idk why margin-bottom doesn't work-->                    
                </p>
            </section>

           
            <section class="jobs">
                <div class="job">
                    <div class="job_info">
                        <div class="job_brief">
                            <h2 class="job_name">Data Engineer</h2>
                            <h3 class="job_head">Job brief</h3>
                            <p class="job_desc"> You will use various methods to transform raw data into useful data systems. Overall, you will strive for efficiency by aligning data systems with business goals. Data engineer skills also include familiarity with several programming languages and knowledge of learning machine methods.</p>
                            <h3 class="job_head">Key responsibilities</h3>
                            <ul class="jobs_ul">
                                <li>Analyze and organize raw data </li>
                                <li>Build data systems and pipelines</li>
                                <li>Evaluate business needs and objectives</li>
                                <li>Interpret trends and patterns</li>
                                <li>Conduct complex data analysis and report on results </li>
                                <li>Prepare data for prescriptive and predictive modeling</li>
                                <li>Build algorithms and prototypes</li>
                            </ul>
                            <h3 class="job_head">Skills and qualifications</h3>
                            <h4>Essentials</h4>
                            <ul class="jobs_ul" id="essential">
                                <li>Previous experience as a data engineer or in a similar role</li>
                                <li>Technical expertise with data models, data mining, and segmentation techniques</li>
                                <li>Knowledge of programming languages  (e.g. Java and Python)</li>
                                <li>Hands-on experience with SQL database design</li>
                            </ul>
                            <h4>Preferable</h4>
                            <ul class="jobs_ul" id="preferable">
                                <li>Great numerical and analytical skills</li>
                                <li>Degree in Computer Science, IT, or similar field; a Master degree is a plus</li>
                                <li>Data engineering certification (e.g IBM Certified Data Engineer)</li>
                            </ul>
                        </div>
                    </div>
                    <aside>
                        <div class="job_reqs">
                            <h4>Job reference number</h4>
                            <p>R2406</p>
                            <h4>Salary</h4>
                            <p>$128,250 - $180,000</p>
                            <h4>Benefits</h4>
                            <p>To help you stay energized, engaged and inspired, we offer a wide range of benefits including:</p>
                            <ol class="jobs_ol">
                                <li>Strong retirement plan, tuition reimbursement, comprehensive healthcare, support for working parents and Flexible Time Off (FTO) so you can relax, recharge and be there for the people you care about.</li> 
                                <li>Employees are eligible for an annual discretionary bonus, and benefits including heath care, leave benefits, and retirement benefits.</li> 
                            </ol>
                            <h4>Applicants please fill this application form and report to Vice Chancellor of HRM</h4>
                            <a href="apply.html">Link to form</a>
                        </div>
                    </aside>
                </div>

                <div class="job">
                    <div class="job_info">
                        <div class="job_brief">
                            <h2 class="job_name">Software Engineer</h2>
                            <h3 class="job_head">Job brief</h3>
                            <p class="job_desc">Builds financial technology products and services to meet the needs of Smarthouse and our clients. Develops software using a host of languages and open source technologies including Java, Python, JavaScript, C#, Cassandra, Angular, React Kubernetes, Kafka, Docker, Solr, iOS and more.</p>
                            <h3 class="job_head">Key responsibilities</h3>
                            <ul class="jobs_ul">
                                <li>Takes ownership of projects and watch your creations be released to thousands of users.</li>
                                <li>Works closely with senior engineers developing specific parts of the Smarthouse platforms</li>
                                <li>Collaborates with users and the product team to design new features.</li>
                                <li>Gains a broad understanding of the infrastructure and the capabilities of Smarthouse </li>
                                <li>Collaborates with colleagues to build innovative products during firm-wide hackathons.</li>
                            </ul>
                            <h3 class="job_head">Skills and qualifications</h3>
                            <h4>Essentials</h4>
                            <ul class="jobs_ul" id="essential">
                                <li>5 years of experience as a Software Engineering, Software Development Engineer, Software Engineer, or related role.</li>
                                <li>Experience with: Data structures and algorithms; Applying design patterns,Angular, Spring, SQL, JavaScript, HTML5, and CSS3. </li>
                                <li>Hands-on experience with building distributed systems and storage technologies such as Cassandra, Redis, and relational database.</li>
                            </ul>
                            <h4>Preferable</h4>
                            <ul class="jobs_ul" id="preferable">
                                <li>2 years of experience with: C# Programming language.</li>
                                <li>Degree in Computer Science, IT, or similar field; a Master degree is a plus</li>
                                <li>Experience with: Modern web application development, and Scala, Apache Spark, Azure Data Factory, Power BI.
                            </ul>
                        </div>
                    </div>
                    <aside>
                        <div class="job_reqs">
                            <h4>Job reference number</h4>
                            <p>R2426</p>
                            <h4>Salary</h4>
                            <p>$110,000 - $160,000</p>
                            <h4>Benefits</h4>
                            <p>To help you stay energized, engaged and inspired, we offer a wide range of benefits including:</p>
                            <ol class="jobs_ol">
                                <li>Strong retirement plan, tuition reimbursement, comprehensive healthcare, support for working parents and Flexible Time Off (FTO) so you can relax, recharge and be there for the people you care about.</li> 
                                <li>Employees are eligible for an annual discretionary bonus, and benefits including heath care, leave benefits, and retirement benefits.</li> 
                            </ol>
                            <h4>Applicants please fill this application form and report to Vice Chancellor of HRM</h4>
                            <a href="apply.html">Link to form</a>
                        </div>
                    </aside>
                </div>
            </section>
        </div>

        
        <footer>
            <div class="row">
                <div class="col" id="special-col">
                    <img src="../images/ava2-removebg-preview.png" class="logo" alt="logo">
                </div>
                <div class="col" id="index_address">
                    <h3>Office<div class="underline"></div></h3>
                    <p class="address">80 Duy Tan<br>
                        Dich Vong Hau, Cau Giay<br>
                        Hanoi, Vietnam
                    </p>
                </div>
                <div class="col" id="index_links">
                    <h3>Links<div class="underline"></div></h3>
                    <ol class="index_links">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="about.html">About Us</a></li>
                        <li><a href="jobs.html">Job Description</a></li>
                    </ol>
                </div>
                <div class="col">
                    <h3>Any Question?</h3>
                    <form method="post" action="http://mercury.swin.edu.au/it000000/formtest.php">
                        <i class="fa-solid fa-inbox"></i>
                        <label for="inquiry" aria-label="inquiry">
                            <input type="text" id="inquiry" name="inquiry" placeholder="Ask here">
                        </label>
                        <button type="submit" class="fa-regular fa-paper-plane" aria-label="submit"></button>
                    </form>
                    <div class="social">
                        <a class="fa-brands fa-youtube" href="https://youtu.be/EXyGv1s0cfk">Youtube video</a>
                    </div>
                </div>
            </div>
        </footer>