 <header class="menu">
            <a href="index.html" class="logo"><img src="../images/ava2-removebg-preview.png" alt="logo"></a>
            <nav class="nav-bar">
                <a href="./index.php">Home</a>
                <a href="./about.php">About Us</a>
                <a href="./jobs.php">Application</a>
            </nav>
            <div class="login">
                <a href="">Login</a>
            </div>
</header>